services:
  db:
    image: postgres:15
    container_name: shortener-db
    environment:
      POSTGRES_USER: shortener_user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: shortener
    ports:
      - "5432:5432"
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"

  app:
    image: my-shortener
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: shortener_user
      DB_PASSWORD: secret
      DB_NAME: shortener
      REDIS_HOST: redis
      REDIS_PORT: 6379

